package io.github.blad3mak3r.cardio.protocol

/**
 * Field type identifiers used in PostgreSQL `ErrorResponse` and `NoticeResponse` messages.
 *
 * Each entry corresponds to a single ASCII byte that precedes the field value on the wire.
 * See the [PostgreSQL protocol documentation](https://www.postgresql.org/docs/current/protocol-error-fields.html)
 * for the full specification.
 *
 * @property byte The ASCII byte that identifies this field in the wire message.
 */
enum class ErrorField(val byte: Byte) {
    /** Severity label (e.g. `ERROR`, `FATAL`, `WARNING`). May be localised. */
    SEVERITY('S'.code.toByte()),

    /** Severity label, never localised. */
    SEVERITY_NON_LOCALIZED('V'.code.toByte()),

    /** SQLSTATE error code (5-character, e.g. `42P01`). */
    CODE('C'.code.toByte()),

    /** Primary human-readable error message. */
    MESSAGE('M'.code.toByte()),

    /** Optional secondary message with additional detail. */
    DETAIL('D'.code.toByte()),

    /** Optional suggestion on how to resolve the error. */
    HINT('H'.code.toByte()),

    /** Character position of the error in the original SQL string (1-based). */
    POSITION('P'.code.toByte()),

    /** Character position in an internal query generated by the server. */
    INTERNAL_POSITION('p'.code.toByte()),

    /** Text of the internally generated query. */
    INTERNAL_QUERY('q'.code.toByte()),

    /** Context in which the error occurred (e.g. call stack for PL/pgSQL). */
    WHERE('W'.code.toByte()),

    /** Name of the schema associated with the error. */
    SCHEMA_NAME('s'.code.toByte()),

    /** Name of the table associated with the error. */
    TABLE_NAME('t'.code.toByte()),

    /** Name of the column associated with the error. */
    COLUMN_NAME('c'.code.toByte()),

    /** Name of the data type associated with the error. */
    DATA_TYPE_NAME('d'.code.toByte()),

    /** Name of the constraint associated with the error. */
    CONSTRAINT_NAME('n'.code.toByte()),

    /** Source-code file name where the error was reported. */
    FILE('F'.code.toByte()),

    /** Source-code line number where the error was reported. */
    LINE('L'.code.toByte()),

    /** Name of the source-code routine that reported the error. */
    ROUTINE('R'.code.toByte());

    companion object {
        /**
         * Returns the [ErrorField] whose [byte] matches [b], or `null` if unrecognised.
         *
         * @param b The byte read from the wire message.
         */
        fun fromByte(b: Byte) = entries.firstOrNull { it.byte == b }
    }
}